# git source https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html

- name: Install elasticsearch pgp key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Import elasticsearch repository
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    filename: /etc/apt/sources.list.d/elastic-7.x.list
    state: present

# move to handler
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Start elasticsearch grafana
  service:
    name: elasticsearch
    state: started
    enabled: yes
