#source https://grafana.com/tutorials/install-grafana-on-raspberry-pi/

- name: Install grafana pgp key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Import grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    filename: /etc/apt/sources.list.d/grafana.list
    state: present

# move to handler
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install grafana
  apt:
    name: grafana
    state: present

- name: Start service grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
